fix(submission): ignore unrecognized "Close" events
Had a few of those in a task queue that were never processed due to an
exception being thrown:

     AttributeError: 'NoneType' object has no attribute 'tags'